### ISSUE TITLE
Cannot read property 'name' of undefined testing serialize

### ISSUE THREAD

**Issue by AMagistroni** [GillianPerard/typescript-json-serializer#100]
When I try to test a component that use serialize, I found this error

Cannot read property 'name' of undefined

Using the application it's work.
I use Jest, here the test(simplified, without component)

```
@Serializable()
export class ClassToTest {
  @JsonProperty() num: number;

  constructor() {}
}

describe('test', () => {

  it('test serialization', () => {
    debugger;
    const obj = new ClassToTest ();
    obj.num= 100;
    const serialized = serialize(obj); // here the error
    const deserialized = deserialize<ClassToTest >(serialized, ClassToTest );
    expect(deserialized .num).toBe(100);
  });
```

the tsconfig.json
```

{
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jest",
      "node"
    ],
    "module": "commonjs",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowJs": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "target": "es5"
  },
  "files": [
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by GillianPerard** [comment]
Hi, let me check.

**Comment by GillianPerard** [comment]
I tested with a little sample and your `tsconfig.json` and  your code and with this `package.json` and `jest.config.js` it works properly.

Could you test with the following `pakcages`/`file` please 😊

package.json

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "@types/jest": "^26.0.14",
    "@types/node": "^14.11.2",
    "jest": "^26.4.2",
    "jest-junit": "^11.1.0",
    "ts-jest": "^26.4.0",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.3",
    "typescript-json-serializer": "^2.4.0"
  }
}
```

jest.config.js

```js
module.exports = {
  coverageReporters: ["text", "lcov"],
  reporters: ["default", "jest-junit"],
  roots: ["spec"],
  transform: {
    "^.+\\.tsx?$": "ts-jest",
  },
};
```

PS: my test file is in a spec folder and call `index.spec.ts`.

**Comment by AMagistroni** [comment]
[SerializeTest.zip](https://github.com/GillianPerard/typescript-json-serializer/files/5310217/SerializeTest.zip)
I've tried but with the same result, so I've created another sample project, and the error is the same.
The code is uploaded. Have you the same result with the code uploaded?

**Comment by GillianPerard** [comment]
Ok, I'll test soon.

**Comment by GillianPerard** [comment]
Hi, sorry to be late. I tested your code and it seems that ReflectMetadata package I used in my lib is not able to find the type/prototype of any value 😕

I think is due to the project technology, I can't do anything for you...

**Comment by bakatrouble** [comment]
Got the same issue with `create-react-app` project

Solved it using following `.babelrc` (overrided default settings using `@jackwilsdon/craco-use-babelrc`):
```
{
  "presets": ["react-app"],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

Setting in `tsconfig.json`:

```    
"emitDecoratorMetadata": true,
    "experimentalDecorators": true,
```

And adding `import "reflect-metadata";` line at the top of `index.tsx`

https://github.com/rbuckton/reflect-metadata/issues/104

**Comment by AMagistroni** [comment]
I've solved the problem inserting in the package.json this

```
"jest": {
    "setupFilesAfterEnv": [
      "<rootDir>/src/setup-jest.ts"
    ],    
  }
```

I think that also `setupFiles `work

and 
`import 'reflect-metadata';`

at the top of setup-jest.ts

Thank you @bakatrouble for your suggestion

**Comment by GillianPerard** [comment]
It's great that you can continue to use my lib!
