### ISSUE TITLE
How to deserialize a generic class

### ISSUE THREAD

**Issue by omarbelkhodja** [GillianPerard/typescript-json-serializer#101]
I'm struggling with the following call that leads to a compiling error `Value of type 'typeof MyClass' is not callable. Did you mean to include 'new'?`

```typescript
const rpcResponse = deserialize<RpcResponse<Data>>(responseJSON, RpcResponse<Data>);
```
Any idea how to fix this please ?

**Comment by GillianPerard** [comment]
It seems yes, there is a bug / a feature to add to support generics!

**Comment by GillianPerard** [comment]
Hi, I'm sorry but it seems that we can't handle (instantiate) generics of generics :/
