### ISSUE TITLE
How to handle constructors?

### ISSUE THREAD

**Issue by fny** [GillianPerard/typescript-json-serializer#102]
Looking for some guidance on this. I get a lot of errors like this:

```
Property 'employees' has no initializer and is not definitely assigned in the constructor. ts (2564)
```

Do you have a recommended work around while using the strictPropertyInitialization flag?

**Comment by GillianPerard** [comment]
Hi, I found this answer, could it help you?

[https://github.com/Microsoft/TypeScript-Vue-Starter/issues/36#issuecomment-371434263](https://github.com/Microsoft/TypeScript-Vue-Starter/issues/36#issuecomment-371434263)
