### ISSUE TITLE
enum serilaization/deserialization error

### ISSUE THREAD

**Issue by LoloActemium** [GillianPerard/typescript-json-serializer#103]
Hello,

I tried to deserialize an object tree in which I have some enum properties (React App).
During the test, I got errors on type.name.toLowerCase() in convertDataToProperty.
I got also an error in castSimpleData on type.toLowerCase().
Looks like it couldn't get the type of my enum.
export enum ELoggingState {
	Stopped = 0,
	Paused = 1,
	Running = 2,
}
So, I modified the source code to get rid of those errors.
Did you ever heard problem with enums ?
If you want, I can create a pull request with my modifications.

Kine Regards,
Laurenr.

**Comment by GillianPerard** [comment]
Hi, thank you for your issue, could you just put here your solution, I'll integrate it!

**Comment by LoloActemium** [comment]
[index.txt](https://github.com/GillianPerard/typescript-json-serializer/files/5494241/index.txt)
Hi,
I won't say it's a "solution".
Check it out and let me know  :)

**Comment by GillianPerard** [comment]
Hi thank you!, Could you just post here a complet example of the object you want to serialize/deserialize and tell me where in the file did you make some changes please?

**Comment by LoloActemium** [comment]
See for details.
#104 Fixing null value problem with enum

**Comment by GillianPerard** [comment]
I fix it in the new version 2.4.1, thank you for your issue/PR 😊
