### ISSUE TITLE
New version onDeserialize definition breaks compatibility

### ISSUE THREAD

**Issue by romgerman** [GillianPerard/typescript-json-serializer#107]
Hey. I saw an update and was excited to try it but unfortunately i've stumbled upon compilation errors in my project.

#98 breaks compatibility with previous versions but it marked as patch version and not major.

This breaks the code because it defines a function as returning an object. But for example in my project i use this for simple data and not for objects.
https://github.com/GillianPerard/typescript-json-serializer/pull/98/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R18

Example from the project i am working on
```js
@JsonProperty({
    name: 'ImageId',
    onDeserialize: (id: number | undefined) => {
        return id ? getUrl(id) : undefined;
    },
})
Image?: string;
```

I think in type definition it should return `any` instead of `{}`.

**Comment by GillianPerard** [comment]
Hi! Oh sorry let me fix this as soon as possible!

**Comment by GillianPerard** [comment]
Hi, I push a new version 2.5.1 that fix this issue!

Thank you again to use my lib and provide some issues/feedback here 😊
