### ISSUE TITLE
@JsonProperty() in getters

### ISSUE THREAD

**Issue by pablomartinezm** [GillianPerard/typescript-json-serializer#114]
Is it possible to add @JsonProperty decorator to a getter function?

```javascript
@Serializable()
class MyClass {
  @JsonProperty()
  get myProperty(): string { return this.myProperty }
}
```

**Comment by pablomartinezm** [comment]
Hi Gillian, sorry for the briefness of my request.
In my code I have domain entities that are created through props and I expose those properties using getters this way:
```javascript
export class TestEntity {
    constructor(private props: TestEntityProps) { }

    get text(): string {
        return this.props.text;
    }
    get is(): boolean {
        return this.props.is;
    }
}
```
In this case I would like to decorate the getters, instead of the object `props` as I show you in the following snippet:

```javascript
@Serializable()
export class TestEntity {
    constructor(private props: TestEntityProps) { }

    @JsonProperty()
    get text(): string {
        return this.props.text;
    }
    @JsonProperty()
    get is(): boolean {
        return this.props.is;
    }
}
```
Does this makes sense?

**Comment by GillianPerard** [comment]
Even with the example, I don't think that my lib could help you as you create your own getters you can directly cast your prop without `JsonProperty`.

**Comment by pablomartinezm** [comment]
Of course in this example does not make sense, but as soon as we have domain models and we want it to serialize them hierarchically to convert them to DTOs it is really handful to have this functionality:

```javascript
@Serializable()
export class User {
    constructor(private props: UserProps { }
    @JsonProperty()
    get id(): Id {
        return this.props.id;
    }
    @JsonProperty()
    get name(): string {
        return this.props.name;
    }
}

@Serializable()
export class TestEntity {
    constructor(private props: TestEntityProps) { }

    @JsonProperty()
    get users(): User[] {
        return this.props.is;
    }
}
```
