### ISSUE TITLE
Deserialize Array

### ISSUE THREAD

**Issue by EphraimNetWorks** [GillianPerard/typescript-json-serializer#119]
Hi, I'm struggling to deserialize an array with this `deserialize<Array<User>>(json, Array<User>)`. I get the error `Argument of type 'User[]' is not assignable to parameter of type 'new (...params: any[]) => User[]'`. How do I go about deserializing an array? Any help is appreciated. Thanks

**Comment by GillianPerard** [comment]
Hi thank you for using my lib.

You cannot directly deserialize an array because it's not a json object.

You can do for example:

```json
{
  "myArray": [
    { "id": 0, "name": "Item 1" },
    { "id": 1, "name": "Item 2" }
  ]
}
```

```ts
@Serializable()
class MyItem {
  @JsonProperty()
  id: number;

  @JsonProperty()
  name: string;
}

@Serializable()
class MyObject {
  @JsonProperty({ type: MyItem })
  myArray: Array<MyItem>;
}

deserialize<MyObject>(myJson, MyObject);
```

I hope it will help you!

**Comment by EphraimNetWorks** [comment]
This works too, thanks for the quick reply

**Comment by hecmec** [comment]
Hello,
first of, thanks for this library.
But I do not understand your answer.
Often we want to de-serialize a JSON of a http request response representing a list of typed objects, like this :
`[
  { "id": 0, "name": "foo" },
  { "id": 1, "name": "bar" }
]`

How am I supposed to de-serialize this, if not like so ??:

`
const personList: Person[] = deserialize<Array<Person>>(requestResponse, Array<Person>);
`

I mean, I could change the json, to wrap an object around the array, but that seems strange.

Thanks

**Comment by GillianPerard** [comment]
Hi, thank you for using my library !

At this moment, you cannot deserialize an array directly ; it must be an object.
I'm currently working (and for a long time) on a new major version (4.0.0) which has lot of breaking changes but one of the new features it will provide is to deserialize an array.

I still have some troubles with React compatibility and I'm very busy at work so I don't achieve this version yet but it comes as soon as possible!

**Comment by hecmec** [comment]
Hello, 
(just in case someone else has the same question)
as for now I just preparse the string of a list
 
`const list = JSON.parse(str);`

and then I map each element

```
    const itemViewList: ItemViewLite[] = list.map((elm) => {
      return deserialize<ItemViewLite>(elm, ItemViewLite);
    });
```

That works ok for me.
Thanks again.
Hector
