### ISSUE TITLE
How to deserialize dynamic property?

### ISSUE THREAD

**Issue by ultimaweapon** [GillianPerard/typescript-json-serializer#121]
Hello, I want to deserialize the following class:

```ts
class Foo {
    type: string;
    value: any;
}
```

The type of `value` will be depend on `type` (e.g. if `type` is `name` the `value` will be `string`). The closest thing I can find to achieve this is using `predicate` but the problems is I can't access `type` from there.

**Comment by GillianPerard** [comment]
Hi, let me check.

**Comment by GillianPerard** [comment]
Hi, sorry for the delay.

I push a new 3.1.0 version that gives you the access to the parent property!

```ts
@Serializable()
class Foo {
    @JsonProperty()
    type: string;
    @JsonProperty({ predicate: (property, parentProperty) => parentProperty.type === 'foo' ? Foo : Bar })
    value: any;
}
```

I hope it will work for you and thank you for your issue!

**Comment by ultimaweapon** [comment]
Awesome!
