### ISSUE TITLE
Separating serializer/deserializer from the type itself

### ISSUE THREAD

**Issue by axos88** [GillianPerard/typescript-json-serializer#122]
I'm pretty sure this one would be a biggy, but for the next major release perhaps I would love to see the serializers/deserializers being separated from the types themselves. 
This would have two main benefits:
  - a foreign class (defined in a library perhaps) can be made serializable by the user code
  - possibly multiple serializers could be defined for the same class (to comply with multiple APIs operating on the data, using different representations)

I would envision it to work something along the lines: 

```
export class LivingBeing {
    id: number;
}

export class Human extends LivingBeing {
    constructor(
        public id: number,
        public readonly birthDate: Date
    ) {
        super();
        this.id = id;
    }
}

@Serializer(LivingBeing)
export interface LivingBeingSerializer {
    @JsonProperty() id: number;
}

@Serializer(Human)
export interface HumanSerializer extends LivingBeingSerializer {
      @JsonProperty('humanId') public name: string,
      public id: number,
      @JsonProperty() public gender: Gender,
      @JsonProperty() public readonly birthDate: Date
}

@Serializer(Human)
export interface HumanSerializer2 extends LivingBeingSerializer {
      @JsonProperty() public name: string,
      public id: number,
      @JsonProperty() public gender: Gender,
      @JsonProperty() public readonly birthDate: Date
}

const human = deserialize<Human>(json, HumanSerializer); // reads name from "humanId"
const human = deserialize<Human>(json, HumanSerializer2); // reads name from "name"
```

Although I do not currently have free time to work on this, I just wanted to put this on the ideas table

**Comment by GillianPerard** [comment]
Hi!

Thank you for the issue.

I assume that I'm not sure I understood correctly the improvement but I see a big problem in these lines:

```ts
@Serializer(LivingBeing) // <---- Here
export interface LivingBeingSerializer {
    @JsonProperty() id: number;
}
```

In typescript, there is no `introspection` possible for a class, even if I pass as parameter the class to the `Serializer` decorator I cannot access the properties except if those properties are initialized atleast with `undefined` or any other value... 

So I must decorate each class AND property to know them without initialization.

**Comment by axos88-da** [comment]
I'm not sure you understood my issue correctly. 

The LivingBeing paramter to signal that (de)serializer should construct that particular type instead of the one that it's being applied on. I saw some meta-cache-magic working under the hood, i think that might be leveraged for this feature as well, doesn't it?

The LivingBeing would also need to be marked with @Serializable of course, but the extra feature here would be the ability to have multiple serializers for the same class.
