### ISSUE TITLE
Inital instance is changed during serialization

### ISSUE THREAD

**Issue by timir0n** [GillianPerard/typescript-json-serializer#123]
Hi!

I think there is a problem.
Why inital instance is mutated by serializer? For example, during beforeSerialization predicate works.
I think, it would be better when result of beforeSerialize() will not modify inital instance, but will be passed as an argument for serialize().

So current implementation can't be used with immutable data instance.
Am I right?

**Comment by GillianPerard** [comment]
Hi, yes I'm pretty sure that I don't think this case in the lib, let me investigate!

**Comment by GillianPerard** [comment]
Hi, could you provide me an example to test with an immutable object please?

**Comment by timir0n** [comment]
Hi.
I'm sorry for delay.

Here is a sample code - https://stackblitz.com/edit/typescript-zjc5kf?file=index.ts

**Comment by GillianPerard** [comment]
Hi, don't worry.

Thank you very much for providing full example!

I'll see what can I implement to fix the problem :)

**Comment by GillianPerard** [comment]
I push a new 3.2.1 version where I store the value before you run `beforeSerialize` and apply again the previous value because I don't want (and can't) create a deep copy (it seems that the metadata are not copied) but I tested with your example and it works properly 😊
