### ISSUE TITLE
Throw an Error if the provided Json does not have the required fields

### ISSUE THREAD

**Issue by Eljoy** [GillianPerard/typescript-json-serializer#133]
Great lib.
As of right now though, it seems, that if for example, the provided json does no have certain JsonProperty field 
the deserialize will simply ignore it. I presume for this case there should be parse Error thrown.

**Comment by GillianPerard** [comment]
Hi, thank you for using my lib!

Typescript has no way to know if a proerty is required or not so the only thing I can do is to add a paramater `required` to the `JsonProperty` decorator and throw an error if this marked property is missing.

**Comment by Eljoy** [comment]
Yep, that would be great.)

**Comment by GillianPerard** [comment]
Do you think that if the the value of the required property is set to `null` or `undefined`, it's considered as `falsy` then throw an error?

Or I throw an error just if the property is not existing?

**Comment by GillianPerard** [comment]
The new version 3.3.0 is now available 😊.

You can set a property as required by doing:

```ts
@JsonProperty({required: true}) myProp: string;
```

Note that if a property from base class is required you don't have to set the extend property as required inside the child class.

**Comment by Eljoy** [comment]
Great, thx!)

**Comment by shcallaway** [comment]
Apologies for resurrecting a dead thread. When serializing a JsonObject, `required: true` doesn't seem to have any effect. I would expect `.serialize(foo)` to fail if foo is missing a required property `bar`. Is this intentional?

**Comment by GillianPerard** [comment]
Hi, by  default with the version 4.x.x it logs the error and does not throw if you want this mechanism, you must pass the option to your `JsonSerializer`.

For  example:

```ts
const serializer = new JsonSerializer({ errorCallback: throwError });
```

`throwError` is provided by the library (as `logError`) but you can provide you own function to handle errors :).

Hope it helps you!

**Comment by Benjamin-L** [comment]
Not sure if it's feasible to do this, but worth noting that with `strictNullChecks`, there _is_ a way to express whether or not a field is required through the type system.

Ideally, I'd like a way to configure typescript-json-serializer such that it throws errors when trying to deserialize input that has a missing field for a field not typed as `| undefined` or a null value for a field not typed as `| null`, without having to manually annotate this. Otherwise, it's possible to break type safety by accidentally forgetting the right annotations.

**Comment by GillianPerard** [comment]
The only thing that I can propose you is to add an option object ton the `JsonObject` with the property `required` that set the option required for all `JsonProperty`. And if for one of them you you want that it is optional you could set it explicitly in the option of the `JsonProperty`.
