### ISSUE TITLE
Allow using optimization and buildOptimizer = true in angular.json

### ISSUE THREAD

**Issue by LucasDshg** [GillianPerard/typescript-json-serializer#135]
Hey man. today i got a crazy bug. When a call serializer two params just disappear.
the bug only happen in `ng build --prod`

I discovered what is cause the bug my app has optimization and buildOptimizer  = true in angular.json 

if i change to false your lib work`s great! So can u do something to allow us run the build with this options igual true?
![Captura de tela 2021-04-22 150332](https://user-images.githubusercontent.com/46797018/115764436-eef0de80-a37b-11eb-8dac-b3dfc3fb9a8f.png)

**Comment by LucasDshg** [comment]
I did some basic test but i cant get the bug. So look this.
Run app wthi ng build --prod
![Captura de tela 2021-04-22 143358](https://user-images.githubusercontent.com/46797018/115760563-d2eb3e00-a377-11eb-9e58-edec1c9cae9a.png)

the product and groupProduct is there but before serialize they gone. Should have CBP_CD_PRODUTO and PGR_CD_PRODUTO_GRUPO and more strange i belive he beforeSerializer to call because i put a `console.log()` there and not show
![Captura de tela 2021-04-22 143623](https://user-images.githubusercontent.com/46797018/115760913-22316e80-a378-11eb-9669-cb85df0e7f3d.png)

![Captura de tela 2021-04-22 143924](https://user-images.githubusercontent.com/46797018/115761291-9409b800-a378-11eb-834d-1b3e9f4fbbae.png)
![Captura de tela 2021-04-22 143902](https://user-images.githubusercontent.com/46797018/115761302-966c1200-a378-11eb-80cd-f4d70cb0cd14.png)

**Comment by LucasDshg** [comment]
I did something wrong?

**Comment by LucasDshg** [comment]
ah this is my angular.json

**Comment by LucasDshg** [comment]
ok no problem man. Just having to find where the bug was already great.
Now lets try to repair. If u need some help could call me.

**Comment by GillianPerard** [comment]
I can't reproduce the bug, I've a project using my lib on Angular with `optimization` and `buildOptimizer` already set to true and everything works correctly.

I use Angular 11.2.7.

Could you provide me the error and an example of code that does not work and the version of Angular you're using please?

**Comment by LucasDshg** [comment]
Hey man de error appears after the ng build --prod. It appears during exetuing de app

**Comment by GillianPerard** [comment]
Could you provide me the error and an example of code that does not work and the version of Angular you're using please?

**Comment by GillianPerard** [comment]
I think I found your problem, it's due to `JsonProperty` inside `constructor` I'll merge the PR #144 soon.

**Comment by GillianPerard** [comment]
Try with the new 3.4.1 version. 😊
