### ISSUE TITLE
Nested array of case : Array<Array<number>> 

### ISSUE THREAD

**Issue by vocal22** [GillianPerard/typescript-json-serializer#136]
Hi GillianPerard, I'm using your product for a while. I think it's a great solution for ts.
Anyway can I ask you a question plz?

@JsonProperty({name:"f",type:Array<number>})
public free: Array<Array<number>>; 

How can I express this nested array of primary types? vs code throw me an error 'Type number[] is missing the following properties from Function'

**Comment by GillianPerard** [comment]
Hi, thank you for using my lib!

Let me check what solution could be the best 😊

**Comment by vocal22** [comment]
I have used your lib for 1 year, it's the best solution I've ever seen. Thanks for you.

**Comment by GillianPerard** [comment]
Could you try to not add the type because as you said it's juste primitive types.

```ts
@JsonProperty("f")
public free: Array<Array<number>>;
```

**Comment by vocal22** [comment]
Thanks man, it works well! you save my day! I thought it too much, so I missed a simple way.

**Comment by GillianPerard** [comment]
You're welcome 😊
