### ISSUE TITLE
"export '__spreadArray' (imported as 'e') was not found in 'tslib'

### ISSUE THREAD

**Issue by raravel** [GillianPerard/typescript-json-serializer#148]
![image](https://user-images.githubusercontent.com/28672888/125150141-6878bb80-e178-11eb-8070-623d0e64a274.png)

I am using a package using `typescript-json-serializer` in the `electron` environment.
At that time, the corresponding error is output.

As a result of the search, it was determined that the issue was similar to the following issue.
https://github.com/ionic-team/ionic-framework/issues/23090

So I ran npm install tslib and the error was resolved.
My guess is that the `tslib` package should be moved from `devDependency` to `dependency`.

**Comment by GillianPerard** [comment]
Thank you for the issue.

I'll put `tslib` as `peerDependencies` because for most of projects that use my lib, they already need `tslib`. I'll just fix the version I need.

**Comment by GillianPerard** [comment]
The new 3.4.4 version is now available :).

**Comment by raravel** [comment]
I confirmed that it works normally.
