### ISSUE TITLE
[FEAT]: generic array

### ISSUE THREAD

**Issue by gxkai** [GillianPerard/typescript-json-serializer#152]
### Description

@Serializable()
export class Pagination<T> {
  @JsonProperty({type: ??}) data: T[];
}
how to fill with “??”

**Comment by GillianPerard** [comment]
Hi, I'm currently on vacation, let me check that when I'm back!

**Comment by gxkai** [comment]
> Hi, I'm currently on vacation, let me check that when I'm back!

Ok,wish your answer.
