### ISSUE TITLE
[FEAT]: Handle object type argument in constructor

### ISSUE THREAD

**Issue by RNm-dove** [GillianPerard/typescript-json-serializer#161]
### Description

Hi, this library is so good! Thank you!

I prefer object(dictionary) type argument to multiple arguments in constructor.

Is there any solution ?

```typescript
import { JsonProperty, Serializable } from 'typescript-json-serializer';

import { Human } from './human';
import { Gender } from './gender';

@Serializable()
export class Father extends Human {
  @JsonProperty() public hobby: string;

  // object type argument
  constructor(args: {
    name: string;
    id: number;
    gender: Gender;
    birthDate: Date;
    hobby: string;
  }) {
    super(args.name, args.id, args.gender, args.birthDate);
    this.hobby = args.hobby;
  }
}
```

https://stackblitz.com/edit/typescript-rqju2w?file=index.ts

### Proposed solution

I think this cloud be done by adding some code.

https://github.com/GillianPerard/typescript-json-serializer/blob/e93742666126e086e0a19d9c787a7dbb86c2e89e/src/index.ts#L238

from 
```typescript
const instance: any = new type();
```

to
```typescript
const instance: any = new type({});
```

**Comment by GillianPerard** [comment]
Hi, thank you for using my lib!

You are right, I just tested it.
Let me make the modification and I publish a new version really soon!

PS: Just for your information I'm working to a new major version (4.0.0) which comes with lot of breaking changes but with new features and simplication of the use :)

**Comment by GillianPerard** [comment]
Done, I push a the new 3.4.5 version to npm, tell me if it works for you!

**Comment by RNm-dove** [comment]
@GillianPerard 
It works well !! Thank you!
