### ISSUE TITLE
[FEAT]: Access a parent value of the JSON to serialize

### ISSUE THREAD

**Issue by KyDenZ** [GillianPerard/typescript-json-serializer#163]
### Description

I am trying your librairie. I am a fan of the possibilities it offers. Thank you !

I want to retrieve a value of my object to serialize from a child class : 

```json
{
  "type": "layout",
  "version": "1.0.0",
  "value": {
    "name": "test"
  }
}

```

```ts
@Serializable()
export class Root {
  @JsonProperty({
    name: 'version',
    type: String,
  })
  version!: string;

  @JsonProperty({
    name: 'value',
    type: Value,
  })
  value!: Value;
}
```

```ts
@Serializable()
export class Value {
  @JsonProperty({
    name: 'name',
    type: String,
  })
  name!: string;

  @JsonProperty({
    name: '../type', // type of the parent element
    type: String,
  })
  type!: string;
}
```

Is there a way to access in my class `value` the `type` value of the parent object?

Thank you !

### Proposed solution

In the source code, I didn't find a solution.
We could add in the functions beforeDeserialize / afterDeserialize... a parameter containing the object to serialize

**Comment by GillianPerard** [comment]
Just a thing you can simplify the code you wrote by doing:

```ts
@Serializable()
export class Root {
  @JsonProperty() version!: string;
  @JsonProperty() value!: Value;
}

@Serializable()
export class Value {
  @JsonProperty() name!: string;
  @JsonProperty({name: 'type', beforeDeserialize: ...})
  type!: string;
}
```

**Comment by KyDenZ** [comment]
Thank you very much!

**Comment by GillianPerard** [comment]
Just for your information, I just release the new major version and it comes with multiple breaking changes.
I'll look at your issue now :).

So I send  again the new  version  of your code according to the version 4.

```ts
@JsonObject()
export class Root {
  @JsonProperty() version!: string;
  @JsonProperty() value!: Value;
}

@JsonObject()
export class Value {
  @JsonProperty() name!: string;
  @JsonProperty({beforeDeserialize: ...}) type!: string;
}
```

**Comment by KyDenZ** [comment]
Thanks for your responsiveness! Let me know if I can help :slightly_smiling_face:

**Comment by GillianPerard** [comment]
Hi, I apologize but I can't provide the parent instance to the before/after functions because I can't assure that the instance is complete, you could retrieve only a part of this instance according to the order of properties.

I've no solution for you, so I close this issue...
