### ISSUE TITLE
[BUG]: `nullishPolicy` set to `remove` does not remove the `null` Object

### ISSUE THREAD

**Issue by sz3lbi** [GillianPerard/typescript-json-serializer#167]
### Version

3.4.4

### Description

I am using the `4.0.0` version which is not available in the drop-down menu when creating an issue.

No matter if I use the `remove` or the `allow` value for the `nullishPolicy`, the `null` objects provided in the JSON still appear in the result array.

Result in the browser console:
```
Array [ {…}, null ]
​  0: Object { recipient: "123", content: "123" }
​  1: null
  length: 2
```

Additionally, I would expect the Serializer with properties set as described not to return the `Nullish` type inside an array. As it still does, I have to filter the result to not have any mismatched types in TypeScript.  
It can be seen in the code snippet provided.

### Reproduction

```json
[
    {
        "recipient": "123",
        "content": "123"
    },
    null
]
```
```ts
import { JsonObject, JsonProperty } from "typescript-json-serializer";

@JsonObject()
export class Message {
  @JsonProperty() recipient: string;
  @JsonProperty() content: string;

  constructor(recipient: string, content: string) {
    this.recipient = recipient;
    this.content = content;
  }
}

```

```ts
import { JsonSerializer, throwError } from "typescript-json-serializer";
import { Message } from "./models/message";

function parseJson(jsonString: string): Message[] {
    function notEmpty<TValue>(value: TValue): value is NonNullable<TValue> {
      return value !== null && value !== undefined;
    }

    const jsonSerializer = new JsonSerializer({
      errorCallback: throwError,
      nullishPolicy: {
        undefined: "remove",
        null: "remove",
      },
    });
    try {
      const deserialized = jsonSerializer.deserializeObjectArray(
        jsonString,
        Message
      );
      return deserialized?.filter(notEmpty) ?? [];
    } catch (error) {
      console.error(error);
      window.alert("Invalid JSON string.");
    }
    return [];
  },
```

### On which OS the bug appears?

Windows 10

### What is your project type?

Node.js

**Comment by GillianPerard** [comment]
Hi, thanks for using my lib.

I found the problem, I'll publish the fix with new tests ASAP!

**Comment by GillianPerard** [comment]
Hi, a the new 4.0.1 version has been released, tell me if it solves your problem :).

**Comment by sz3lbi** [comment]
Yes, now it works fine.  
It still shows the `Nullish | (Message | Nullish)[]` type, but when I use casting `as Message[]`, I no longer need to look for empty elements.  
Thanks.
