### ISSUE TITLE
[FEAT]:  Support Instance of Type for Deserialize

### ISSUE THREAD

**Issue by dhkatz** [GillianPerard/typescript-json-serializer#170]
### Description

Some of the class types I want to deserialize have needed constructor arguments that aren't parsed from the JSON data.

For example:

```typescript
@JsonObject()
class Person {
  @JsonProperty()
  public name: string

  public constructor(public client: Client) {
    // Do stuff with client
  }
}
```

Right now there is no way to handle this case as a new object is constructed each time:

https://github.com/GillianPerard/typescript-json-serializer/blob/9eceb35a9c8fb939cdf2fe32585fe260bfe92a13/src/json-serializer.ts#L80

### Proposed solution

In a similar library I've written I've found the following to work as a solution. Allow for an instance of T as well.

This would require changing the signature(s) to:

```typescript
// Notice the Type<T> | T
deserializeObject<T extends object>(obj: string | object, type: Type<T> | T): T | Nullish {
```

From what I can tell this would not be a breaking change, as you don't use `type` for anything other than the construction of a new object.

```typescript
const instance = typeof type === 'function' ? new type({}) : type;
```

There might be a better way you'd prefer to do this but that's probably the simplest.

If you want to get a bit more complex you could write:

```typescript
const instance = is_constructor(type) ? new type({}) : type;

function is_constructor<T = any>(f: unknown): f is Type<T> {
  if (typeof f !== 'function') {
    return false
  }

  try {
    Reflect.construct(String, [], f)
  } catch (e) {
    return false
  }
  return true
}
```

I haven't tested this with your specific code but this is a [very definitive way](https://stackoverflow.com/a/46759625/11141504) to check if something is a constructor. It's what I ended up using in my older library but to be honest `typeof type === 'function'` should probably cover most cases.

**Comment by GillianPerard** [comment]
Hi thank your for the proposal :)

I'll integrate it asap!

**Comment by GillianPerard** [comment]
The new version 4.1.0 has been released! Tell me if it works for you :).

**Comment by dhkatz** [comment]
Thank you :)
