### ISSUE TITLE
[BUG]: isNullish isn't exported

### ISSUE THREAD

**Issue by brettswift** [GillianPerard/typescript-json-serializer#176]
### Version

4.0.1

### Description

It seems like isNullish isn't exported.   I'm just refactoring to upgrade to 4.x.  

I am just doing a Nullish check after deserializing - but have to do a deep import. 

```
import { isNullish } from "typescript-json-serializer/dist/helpers";
~~ 
const schema = serializer.deserializeObject<ConfigSchema>(object, ConfigSchema);
  if(isNullish(schema)) {
      throw Error("Unable to parse config schema.")
  }
```

Maybe I'm mistaken by the intended usage ? 

### Reproduction

code sample above. 

The version drop down doesn't let me pick 4.1.1, but that is the version i have. 

### On which OS the bug appears?

compile time

### What is your project type?

Typescript (other)

**Comment by GillianPerard** [comment]
Hi thanks for using my lib!

Try the new version 4.2.0 :)

**Comment by brettswift** [comment]
Cool. Thanks for authoring it :)
