### ISSUE TITLE
Support for predicate function

### ISSUE THREAD

**Issue by GillianPerard** [GillianPerard/typescript-json-serializer#19]
Example:

```typescript
@JsonProperty({}, (animal: Animal) => {
    return animal['isPoisonous'] ? Snake : Panther;
})
public pantherOrSnake: Panther | Snake;
```

**Comment by Slion** [comment]
I have something very similar to that example but it looks like my predicate is not called for some reason.
```
    // Property that can be Panther or Snake type
    // Use again the predicate function
    @JsonProperty({ type: snakeOrPanther })
    mascot: Panther | Snake;
```
What am I missing?

**Comment by Slion** [comment]
> Which version do you use?
4.01
> Can you send your exemple with the predicate function please?

```TS
const checkEventType = aEvent => {

    Log.d("CHECK TYPE");

    return aEvent &&
        (aEvent['iType'] == MatchEventType.Goal
            || aEvent['iType'] == MatchEventType.OpponentGoal) 
        ? MatchEventScore
        : MatchEvent;
};


@JsonObject()
export class MatchEventPoint extends Point {

    constructor(aEvent: MatchEvent, aX: number, aY: number) {
        super(aX,aY);
        this.iEvent = aEvent;
    }

    @JsonProperty({ name: "iEvent", type: checkEventType })
    iEvent: MatchEvent | MatchEventScore;
}
```

**Comment by GillianPerard** [comment]
Hi, I tested it and it works for me.

Could you send me the full example with the ata you want to deserialized and the result that you want please.

**Comment by Slion** [comment]
I can't easily send much more of the code I'm afraid but I guess I'll have to do my homework there to try find out what I'm missing then. If it works on your side the issue is either on the encapsulating objects or with the way I do the deserialization.

**Comment by Slion** [comment]
I got it to work! Turns out the parent object had an array declared like that:

```
    @JsonProperty()
    iEventPoints: MatchEventPoint[];
```

I needed to specify the type of the array items, thus:
```
    @JsonProperty({ type: MatchEventPoint })
    iEventPoints: MatchEventPoint[];
```

I actually ran through that same issue when I first deployed your framework so I should have thought about it really. Thanks for your time again ❤👍
Maybe you could log some warning when deserializing an array without specifying the type? Just to make it foolproof 😁

**Comment by GillianPerard** [comment]
Oh yes it could help!

You're welcome :)

**Comment by Slion** [comment]
> Maybe you could log some warning when deserializing an array without specifying the type? Just to make it foolproof 😁

> Oh yes it could help!

Something that says:
`WARNING: JsonProperty array 'myProperty' does not specify a type. Specify 'type: any' to silence this warning.`

**Comment by GillianPerard** [comment]
If the items are of type `object`

**Comment by Slion** [comment]
> If the items are of type `object`

FTFY, you know best 😁 just my two cents really.
