### ISSUE TITLE
[FEAT]: Provide default value for JsonProperty

### ISSUE THREAD

**Issue by ToyWalrus** [GillianPerard/typescript-json-serializer#197]
### Description

First off, this library is very helpful, thank you!

I was wondering if it'd be possible to add something like a default value when using `@JsonProperty()` decorator. Currently if the supplied JSON in the `deserialize()` function doesn't have a key whose property is marked as `required`, it'll use the `errorCallback` but doesn't allow for any "fixing" of the json.

If there was a `defaultValue` option, if a field did not exist on the JSON provided during deserialization, then the `defaultValue` would be used.

### Proposed solution

Update `JsonPropertyOptions` with
```ts
defaultValue?: IOProto | string | number | boolean // etc...
```

Including `IOProto` would allow the default value to be dynamically created as well, if a constant value wasn't used.

**Comment by hookSSi** [comment]
Yeah, I really need it, too.

**Comment by GillianPerard** [comment]
Hi, sorry to be late.

I found a bug with the required feature.
I my mind you could define a default value as you do in typescript.

```ts
@JsonObject()
class Foo {
  @JsonProperty({required: true})
  bar: string = 'bar';
}
```

But it seems I don't check if the default value is set or not.

Do you think this fix is enough for you or you really need the possibility to set defaultValue in the JsonProperty params? And if yes, explain your point.

**Comment by GillianPerard** [comment]
I created an issue for the bug: #201.

**Comment by GillianPerard** [comment]
The new version 6.0.0 is here.

You could now define a default value for a property just using typescript:

```ts
@JsonObject()
class Foo {
  @JsonProperty({ required: true })
  bar: string = 'bar';
}
```
