### ISSUE TITLE
[BUG]:  Deserialize returning empty object in string property

### ISSUE THREAD

**Issue by m4kz** [GillianPerard/typescript-json-serializer#200]
### Version

5.1.0

### Description

When I deserialize the class below from `{"some": "something"}`, i get a weird result

uid becomes an empty object, while name is undefined,.

Shouldn't uid also be undefined?

This is the resukt i get:

```
name: undefined
some: 'something'
uid: {}
```

### Reproduction

class:
```
@JsonObject()
export class BaseModel {
    @JsonProperty()
    uid?: string;      
    @JsonProperty()
    some?: string|null;
    @JsonProperty() 
    name?: string | null; 
    constructor(uid?: string, some?: string | null, name?: string | null ) {
        this.uid = uid;
        this.some = some;
        this.name = name;
     }
}
```
Deserialize:
`const deserializedbm : BaseModel= <BaseModel2>defaultSerializer.deserialize<BaseModel>({"some": "something"}, BaseModel2);
`

### On which OS the bug appears?

Ubuntu

### What is your project type?

NodeJs

**Comment by GillianPerard** [comment]
Hi, thanks for using my lib.

You're right, there is weird behavior there.

Until I fix, you could declare your class as:

```ts
@JsonObject()
export class BaseModel {
    @JsonProperty()
    public uid?: string;

    @JsonProperty()
    public some?: string | null;

    @JsonProperty() 
    public name?: string | null;
}

```

**Comment by m4kz** [comment]
![image](https://user-images.githubusercontent.com/5706828/227496005-ddd55b2e-1fa8-4b2f-960d-cdc28ecab6e5.png)
Thank you, but I don't think it makes a difference

**Comment by GillianPerard** [comment]
Yes indeed, let me fix asap.

**Comment by m4kz** [comment]
Could be possible to have default configurable? either in JsonProperty? or in JsonSerializer?
```

const customSerializer = new JsonSerializer({
//Default type
defaultType:  null
})
```

**Comment by GillianPerard** [comment]
Perhaps in the JsonObject, I could create a param to provide default params for the constructor and if no one is set then i provide undefined.

**Comment by GillianPerard** [comment]
The new version 6.0.0 is here.

You have nothing to do, your could should work now.
But I fou want you can specify the default values for the params of your constructor directly inside the `JsonObject`:

```ts
@JsonObject({ constructorParams: [undefined, null, null] })
export class BaseModel {
    @JsonProperty()
    uid?: string;      
    @JsonProperty()
    some?: string|null;
    @JsonProperty() 
    name?: string | null; 

    constructor(uid?: string, some?: string | null, name?: string | null ) {
        this.uid = uid;
        this.some = some;
        this.name = name;
     }
}
```
