### ISSUE TITLE
[FEAT]: convert typescript property to the value in @JsonProperty name during serialization

### ISSUE THREAD

**Issue by MisterMunchkin** [GillianPerard/typescript-json-serializer#205]
### Description

Hi,

First of all, thanks for this project it's been really useful.

Is there a way where we can have the name value in @JsonProperty replace the property names during serialization? 

**Example**
```
export class NotionProp {
  @JsonProperty({name: 'phone_number'})
  phoneNumber?: string;
  ...
}
...

const serializer = new JsonSerializer();
const pageRequest = new NotionProp();

pageRequest.phoneNumber = '12346688';
const serialized = serializer.serializeObject(pageRequest);
```

Proposed Output:
```
{
 phone_number: '12346688'
}
```
Current Output:
```
{
 phoneNumber: '12346688'
}
```

**Comment by mn4367** [comment]
Unless I'm missing or misunderstanding something, this is already supported? If you search for the string `humanId` in the [README.MD](https://github.com/GillianPerard/typescript-json-serializer/blob/master/README.md) you'll find an example which does exactly what you are proposing.

**Comment by MisterMunchkin** [comment]
Yea I'm not sure what the problem is now because I tried creating a stackblitz for it and can't replicate the issue I'm having on my repo.

It might be that I'm using the beta NextJs appDir but yea not sure right now.

**Comment by MisterMunchkin** [comment]
I tried making the stackblitz mirror what I currently have better and was able to replicate it: https://stackblitz.com/edit/nextjs-vaprea?file=classes/test.ts

It looks like it stops working once I add a beforeSerialize that will turn the array into an object with a custom key while also removing an element.

I haven't really locked down what stops it from working exactly, but after I added the beforeSerialize that's when I was able to replicate my issue.

**Comment by GillianPerard** [comment]
Yes, the `before...` and `after...` functions are used to manipulate the inner data, not to modify the data structure.

In the example you published in Stackblitz, you can just rename the `id` by `page_id` manually, but I assume that your code is way more complex than your example ahah.

Just think that as you modify the structure before serialization, the sub-properties will not be passed to the serializer and will be returned without any kind of manipulation...

So I can close the issue?
