### ISSUE TITLE
Question: What is the best way to convert strings to numbers for deserialization? 

### ISSUE THREAD

**Issue by jnovak-SM2Dev** [GillianPerard/typescript-json-serializer#215]
I'm trying to parse objects that have a string response into numbers, but I don't see how I can handle that easily without making custom serializers and deserializers and adding them to every property.

```
export class MyClass {
  @JsonProperty({ name: 'Name' })
  name: string;

  @JsonProperty({ name: 'age' })
  age: number;
}
```
In the example above, `age` would come through as a string, but need to be parsed to be a number.

**Comment by GillianPerard** [comment]
Hi, there is no other way than using custom before/after serialize/deserialize functions.

But too avoid to repeat these functions everywhere you stored a number as string, you could do the following:

```ts
const convertStringNumber = {
  beforeDeserialize: (value: string) => Number(value),
  afterSerialize: (value: number) => value.toString()
}

export class MyClass {
  @JsonProperty({ name: 'Name' })
  name: string;

  // you don't need to specify the name of the json property if it fits the class property name
  @JsonProperty(convertStringNumber)
  age: number;
}
```

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard Is there a way to pass both and a name in a similar manner to what you showed?

**Comment by jnovak-SM2Dev** [comment]
Yes. That's perfect. Thanks!
