### ISSUE TITLE
Question: Serialize doesn't seem to do anything

### ISSUE THREAD

**Issue by jnovak-SM2Dev** [GillianPerard/typescript-json-serializer#216]
I'm confused what `serialize` is supposed to do. It doesn't seem to actually convert the property names or convert to JSON.

**Example:**

```
@JsonObject()
export class MyClass {
  @JsonProperty({ name: 'Name' })
  name: string;

  @JsonProperty({ name: 'Age' })
  age: number;
}
```

When I `serialize` the object, I just get the following generic object
```
{ 
    name: '1',
    age: 2
}
```

Shouldn't the object values be capitalized like they are in the JsonProperty name for the class? Shouldn't it also be JSON?

**Comment by GillianPerard** [comment]
I think you forgot the `JsonObject` decorator on top of your class.

```ts
@JsonObject()
export class MyClass {
  @JsonProperty({ name: 'Name' })
  name: string;

  @JsonProperty({ name: 'Age' })
  age: number;
}
```

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard You're right, I forgot to put that above, but I do have it in my code, and it still does what I wrote above.

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard I figured it out. If you don't manually set the arguments, it does not work. For example the code below does not work.

```
const myObj: MyClass = {
      name: '1',
      age: 2,
    } as MyClass;
```
Is there a way to set all the properties like the code above and still have it work?

**Comment by GillianPerard** [comment]
It does not work because you dont create a real class, you just cast a js object as a class, not instantiate it.

You could do the following

```ts
@JsonObject()
export class MyClass {
  constructor(
    @JsonProperty({ name: 'Name' }) name: string,
    @JsonProperty({ name: 'Age' }) age: number
  ) {}
}

const myObj = new MyClass("1", 2);
```

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard Yeah that would work, but there are a lot of properties on my real class and there are other decorators in it, so putting everything in the constructor would be a mess. I think I found a way to do it though.

```
const myObj: MyClass = Object.assign(new MyClass(), {
      name: '1',
      age: 2,
    });
```
That seems to serialize properly.

**Comment by GillianPerard** [comment]
Ok perfect, so can I close the issue?

**Comment by jnovak-SM2Dev** [comment]
Yep, sorry. All good.
