### ISSUE TITLE
formatPropertyName on serialize

### ISSUE THREAD

**Issue by jnovak-SM2Dev** [GillianPerard/typescript-json-serializer#217]
Sorry, for spamming questions. Last one.

If I set the `JsonSerializer` to have a prefix, it doesn't seem to add it in when I `serialize` is that the expected behavior? Shouldn't it add it the prefix?

```
const mySerializer = new JsonSerializer({
      formatPropertyName: (propertyName: string) => `_${propertyName}`,
    });
```

**Comment by GillianPerard** [comment]
Hi, no problem.

No it's supposed to work. Could you provide the full example please?

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard Sorry, took a bit to get back to this. So the way you have it setup is, if I override the name with the `name` property on the `JsonProperty` decorator, it will not use `formatPropertyName`.

**Comment by GillianPerard** [comment]
Yes, it's the behavior.

The global formater is overriden by the name you set in the JsonProperty.

**Comment by jnovak-SM2Dev** [comment]
@GillianPerard Yeah that doesn't really make sense for how that should work in my opinion. For example i'm using it to convert params for SOAP. It needs to add the `tns::` prefix to everything. The name coming in and going back to the SOAP API is different, but I obviously want the prefix. For example I call it `firstName` in my object, but SOAP uses `FName`. I want it to become `tns::FName` when it sends to SOAP and parse that when it gets a response from SOAP. The way it works now is the prefix just doesn't work with the different name so it becomes `FName`, which in my opinion completely defeats the purpose of the prefix.

**Comment by jnovak-SM2Dev** [comment]
I made a fork with this working the way I think makes more sense, so I'll close this. But I think this should be handled this way in general, since it's more intuitive in my opinion.
