### ISSUE TITLE
Serialization not working at all?

### ISSUE THREAD

**Issue by zicho** [GillianPerard/typescript-json-serializer#218]
I feel like I am missing something obvious. I am trying to deserialize JSON returned from an API but however I try I cannot get it to work.

I have created a very simple example to recreate my issue.

```
// test class to deserialize

@JsonObject()
export class User {
  @JsonProperty() public userId: string;

  @JsonProperty() public role: string;

  @JsonProperty() public username: string;

  constructor(userId: string, role: string, username: string) {
    this.userId = userId;
    this.role = role;
    this.username = username;
  }
}
```

And then, I try various ways to deserialize it

```
const serializer = new JsonSerializer();

const userCreatedByConstructor: User = new User("123456", "admin", "john_doe");
const userCreatedManually: User = {
    userId: "123456",
    role: "admin",
    username: "john_doe",
};

const serializedUser = serializer.serialize(userCreatedManually);
const serializedUser2 = serializer.serialize(userCreatedByConstructor);

const userManual = serializer.deserialize(userCreatedManually, User);
const userConstructor = serializer.deserialize(userCreatedByConstructor, User);
const userSerialized = serializer.deserialize(serializedUser, User);
const userSerialized2 = serializer.deserialize(serializedUser2, User);
```

But all of these end up with all properties as "undefined". 

I don't understand why this is not working?

**My tsconfig has `emitDecoratorMetadata` and `experimentalDecorators` both set to true.**

**Comment by GillianPerard** [comment]
Hi, i just test your code on Stackblitz and it works properly.

Do you use a framework?

**Comment by zicho** [comment]
Yes, I use React, but this file is pure typescript. Sent from Android deviceOn 14 Dec 2023 16:09, Gillian Pérard ***@***.***> wrote:
Hi, i just test your code on Stackblitz and its works properly.
Do you use a framework?

**Comment by GillianPerard** [comment]
React does not support decorator and metadata properly you have to add some plugins for babel to make it work but I'm not react dev so I can't help you more.

There are some topics in the issues maybe it can help.

**Comment by zicho** [comment]
All right, I will look into it. Thank you.
