### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by deanbiltup** [GillianPerard/typescript-json-serializer#229]
### Description

I realize this is out of scope for this project but perhaps you might consider it.  I would do this if I knew how but I come from java-land where I have implemented this all.  I am new to typescript and eventually will do this if someone else does not get to it first....

It would be amazing if there was another project clientapiGen and serverScaffoldingGen that would generate api to http requests (all POST like grpc does it even in face of a simple GET, gRPC is still all POST).  an example API we have is below and like gRPC, we enforce, one request only which helps with forwards compatibility (ie. adding a param breaks server and client compile while adding a field does not ;) ).   All fields in all our DTO's and sub-DTOs are optional since things shift around as things grow just like the gRPC standard.

generating the client for all APIs makes life much easier and generating scaffolding does as well.

export abstract class ChatApi {

    abstract fetchFirestoreToken(request: FetchTokenRequest): Promise<FetchTokenResponse>;

    abstract fetchGroups(request: FetchGroupsRequest): Promise<FetchGroupsResponse>;

    abstract fetchMessages(request: FetchMessagesRequest): Promise<FetchMessagesResponse>;

    abstract updateTime(request: UpdateTimeRequest): Promise<UpdateTimeResponse>;
}

example for clients is we do this for every method
    async fetchGroups(request: FetchGroupsRequest): Promise<FetchGroupsResponse> {
        const url = `${this._svcBaseUrl}/fetchGroups`;
        return await this._clientUtil.fetchAndTranslate(url, request);
    }

example for server is we do this for every method

        this.app.post(`${basePath}/fetchGroups`, async (req: Request, res: Response) => {
            return translateOrReturn<FetchGroupsResponse>(this._logger, res, async () => {
                const request = Object.assign(new FetchGroupsRequest(), req.body);
                return await this._controller.fetchGroups(request);
            });
        });

a cool thing would passing in controller, and express app to new ServerBinding(app, ChatApi, chatApiController);

Now, with a monorepo, you have all your APIs being used by client and server so developers do not break compatibility on accident.

**Comment by GillianPerard** [comment]
You're right it could be a good library but it's not the goal of this one and I don't have the time to do it.
