### ISSUE TITLE
[BUG]: beforeDeserialize / afterSerialize not working when in object that is in array?

### ISSUE THREAD

**Issue by deanbiltup** [GillianPerard/typescript-json-serializer#231]
### Version

6.0.0

### Description

AFAICT, this is not working BUT works when I am not in an array -> 
```

@JsonObject()
export class OutlineDto {
    @JsonProperty({
        beforeDeserialize: stringToStageEnum,
        afterSerialize: stageEnumToString
    })
    public stage?: StageEnumDto;
}

@JsonObject()
export class FetchProposalsResponse {
    @JsonProperty()
    public proposals?: OutlineDto[] // tried Array<OutlineDto> here as well
    @JsonProperty()
    public hasMoreData?: boolean
    @JsonProperty()
    public totalSize?: number;
}

@JsonObject()
export class FetchSingleOutline {
    @JsonProperty()
    public proposal?: OutlineDto
}
```

serialize FetchSingleOutline serialize works and serialize FetchProposalsResponse results not invoking my serializers to translate to a 'single key' and instead prints the object which has two fields key, guiLabel.

My enum looks like so for usage in the GUI value=key, label=guiLabel -> 
```
export const StageEnumDto = {
    DESIGNING: { value: 'designing', description: 'Designing' },
    NEGOTIATING: { value: 'negotiating', description: 'Negotiating' },
    BOOKED: { value: 'booked', description: 'Booked' },
} as const;
export type StageEnumDto = typeof StageEnumDto[keyof typeof StageEnumDto];
export const stageEnumToString = (classSize?: StageEnumDto): string | undefined => {
    console.log(`serializeing stage=${classSize}`);
    if(!classSize)
        return null;
    return classSize.value;
};
export const stringToStageEnum = (str?: string): StageEnumDto | undefined => {
    console.log(`string to sstage=${str}`);
    if (!str) return undefined;

    const entry = (Object.entries(StageEnumDto) as [keyof typeof StageEnumDto, StageEnumDto][])
        .find(([, value]) => value.value === str);

    if (entry) {
        return entry[1];  // Return the corresponding enum value
    }

    throw new Error(`Invalid class type string: ${str}`);
};
```

### Error

```Text
no error, just is not writing out the correct json
```

### Reproduction

above is the code in the description for the objects.

oh, and I use     private defaultSerializer = new JsonSerializer({
        additionalPropertiesPolicy: 'allow'
    });

### On which OS the bug appears?

macOS

### What is your project type?

nodejs & angular both

### On which build mode the bug appears?

both

### Anything else?

nope

**Comment by deanbiltup** [comment]
specificaly the json it writes out when inside the OutlineDto array is { value: 'designing', description: 'Designing' } instead of "stage":"designing" but it works and writes out "stage":"designing" when I serialize FetchSingleOutline.

**Comment by GillianPerard** [comment]
In typescript I can't determine the item type of an array thanks to the metadata, so you've to specify it as in this example: 

```ts
@JsonObject()
export class Organization extends Society {
    @JsonProperty({ type: Zoo }) zoos: Array<Zoo>;
    ...
}
```

**Comment by deanbiltup** [comment]
ohhhhh, THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
