### ISSUE TITLE
Support constructor parameter decorators

### ISSUE THREAD

**Issue by civilizeddev** [GillianPerard/typescript-json-serializer#28]
Hi, thank you for maintaining this project.

I hope this could be supported in the near future.

## Current

```
@Serializable()
export class Student {
  @JsonProperty()
  public readonly studentId: number

  @JsonProperty()
  public readonly name: string

  @JsonProperty()
  public readonly grade: number

  constructor(
    readonly studentId: number,
    readonly name: string,
    readonly grade: number
  ) {
    this.studentId = studentId
    this.name = name
    this.grade = grade
  }
}
```

- verbose
- redundant code

## Wanted

```
@Serializable()
export class Student {
  constructor(
    @JsonProperty()
    public readonly studentId: number,
    
    @JsonProperty()
    public readonly name: string,
    
    @JsonProperty()
    public readonly grade: number
  ) {}
}
```

- succinct

## References

- [TypeScript Parameter Decorators](https://blog.wizardsoftheweb.pro/typescript-decorators-parameter-decorators/)

**Comment by GillianPerard** [comment]
Hi, thanks to you to suggest some enhancement!

I'm going to try to add this feature as faster I can.

**Comment by GillianPerard** [comment]
Hi, I've updated the lib, could you check if it works for you please?

**Comment by civilizeddev** [comment]
I don't think it's working yet. Can you please check the test cases I added?

**Comment by GillianPerard** [comment]
Hi, I read it but I’m on holidays and I can’t test it right away.

I’ve updated the data I use to test my lib (see panther.ts) and the tests passed.

Let me check on Wednesday.

**Comment by civilizeddev** [comment]
I'm afraid your `Panther` class takes just 1 argument with `@JsonProperty()`.
It looks like it would fail when there are multiple arguments with `@JsonProperty()` passed.
My test cases describe it.

Take your time. Thanks.

**Comment by GillianPerard** [comment]
Hi, just a little error.
I fixed and I updated my own tests.

Tell me if it does the trick now!

**Comment by civilizeddev** [comment]
Now it works.
It's amazing that you implemented this earlier than I expected.

Thank you.

**Comment by GillianPerard** [comment]
You're welcome, thanks you too :).
