### ISSUE TITLE
Support a Reverse Predicate Function

### ISSUE THREAD

**Issue by toothlessG22** [GillianPerard/typescript-json-serializer#29]
Would it be possible to support a reverse predicate function?

Right now I have a problem where I have JSON with a lot of extra layers:

JSON:
```
{
    A: {
        B: {
            C: {
                D: "value"
             }
         }
    }
}
```
Target Class:
```
class A {
    private D: string;
}
```

Right now I solve this using a predicate function:
```
function(obj)
{
    return obj["C"]["D"];
}
```

However, this does not work with deserialization. Having an unpredicate function (need a better name) would allow a function like this:
```
function(obj)
{
    return { B: { C: { D: obj } } }
}
```

That would allow deserializing back to the original extra layer state.

**Comment by GillianPerard** [comment]
Hi, 

Thanks for your feedback.

Just to clarify, currently predicate is only used by `deserialize`, are  you sure it does not work with `deserialize` or this is a mistake and it's `serialize` that does not work ?

**Comment by toothlessG22** [comment]
Whoops, yep it does not work with the serialization. Sorry about that!

**Comment by GillianPerard** [comment]
Ok no problem!
