### ISSUE TITLE
Serialize an external class

### ISSUE THREAD

**Issue by bergwerf** [GillianPerard/typescript-json-serializer#45]
I have a class that has member of the type `THREE.Vector3` (a 3 component vector from three.js). Can I define a custom serialization function for this member? (using `.toArray()` and `.fromArray()`)

**Comment by GillianPerard** [comment]
Hi, could you show me an example of your class, the object you want to serialize and the result that you want please?

**Comment by bergwerf** [comment]
```
import * as THREE from 'three';
import { Serializable, JsonProperty } from 'typescript-json-serializer';

@Serializable()
class Thing {
  constructor(@JsonProperty() public position: THREE.Vector3) { }
}
```

I want to serialize `new Thing(new THREE.Vector3(1, 2, 3));` into:

```
{
  "position": [1, 2, 3]
}
```

The `THREE.Vector3.toArray` and `THREE.Vector3.fromArray` somehow have to be connected to the serialization and de-serialization.

**Comment by GillianPerard** [comment]
Hi,

I added a new property to pass to the `JsonProperty` decorator called `transform` that takes two function properties: `onDeserialize` and `onSerialize`.

Could you retrieve my branch `feature/json-property-transform` and test if it does the job please?
For more information about the `transform` property , I let you check the updated README.

**Comment by LexRiver** [comment]
Hi, @GillianPerard 
great package!
Today I was missing this feature also!
I was trying to serialize Decimal.js

I have tested your branch and it works perfect for me.
Please publish to NPM when possible.

And I suggest using a more simple interface like this:
```typescript
{ name?: string, predicate?: Function, deserialize?: (json:any)=>T, serialize?: (value:T)=>any }
```

-- 

A little offtopic but is it possible to get rid of double ```T``` here?
```typescript
deserialize<T>(json, T): 
```

**Comment by bergwerf** [comment]
Nice! I'll try this out when I have time :) (feel free to publish if you think it is good enough of course)

**Comment by GillianPerard** [comment]
Hi,

According to the @LexRiver suggestion, I replaced the `transform` property by `onSerialize` and `onDeserialize` properties.

To answer to your offtopic, I know that set `T` twice is annoying but I can't do it in other way because I could not instantiate `T` without it, I'm sorry.

I'm glad you're using my library and I thank you to send me you experiences!

I already published the new `1.4.0` version on NPM, so I close this issue, feel free to open it again if you have some other remarks about this feature or open another if you have new needs 😊.

**Comment by LexRiver** [comment]
great!

according to this article
https://blog.rsuter.com/how-to-instantiate-a-generic-type-in-typescript/

it's possible to use your exact method just like this:
```typescript
deserialize(json, T)
```
instead of
```typescript
deserialize<T>(json, T)
```

**Comment by GillianPerard** [comment]
I suppose that you talk about the comment with the following code:

```typescript
private handleResponse(response: any, type: (new (any) => T)): T {
    if (response.text() === '') {
        return new type(null);
    } else {
        return new type(response.json());
    }
}
```

The only thing that permits to not use `<T>` is because the `T` is declared by the class the method belongs to.

In my case it's just a function, I tried to remove it but get an error.

And if you talk about the example given in the post, he use the same method as me ^^.

**Comment by LexRiver** [comment]
No no, you don't need to change anything.
It's just the way your exported ```deserialize``` function could be called.
I've checked and it works great.
You could just change the readme.

**Comment by GillianPerard** [comment]
😦 you're right, I misunderstood what you were talking about, sorry.

I just tested it and it works properly, let me publish a fix!

**Comment by GillianPerard** [comment]
`1.4.1` published!

**Comment by LexRiver** [comment]
oh yes, great!

**Comment by gius** [comment]
Hi, I'd like to elaborate more on the issue title - is it possible to (de)serialize external class? I mean a class that I am not able to edit and apply decorators in the source code. 

Something like:
```
applyDecorators(ExternalClass, { @JsonProperty foo: string }) // @JsonObject will be applied on ExternalClass, @JsonProperty on ExternalClass.foo
```

Or maybe even better
```
applyDecorators(ExternalClass, { foo: { /* JsonPropertyParams */ } })
```
