### ISSUE TITLE
Cannot read property of 'name' of undefined

### ISSUE THREAD

**Issue by jaredbaszler** [GillianPerard/typescript-json-serializer#57]
When I package a simple data transfer to a 3rd party API to an Winx64 .exe via the node pkg package, I get this error.  

```
C:\Users\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\build>registria-win.exe -s "daisy" -b "LIN01" -r "1049315-1049318
TypeError: Cannot read property 'name' of undefined
    at convertDataToProperty (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\node_modules\typescript-json-serializer\index.js:164:24)
    at C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\node_modules\typescript-json-serializer\index.js:92:29
    at Array.forEach (<anonymous>)
    at Object.deserialize (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\node_modules\typescript-json-serializer\index.js:90:10)
    at RegistriaData.<anonymous> (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\build\registriaData.js)
    at step (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\build\registriaData.js)
    at Object.next (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\build\registriaData.js)
    at fulfilled (C:\snapshot\Jbaszler\OneDrive\Documents\Personal Stuff\Larson\Code Projects\Registria\registriaBackEnd\build\registriaData.js)
```

It runs just fine in the dev/debug environment.  I've attached the few files that are in play for this.  
[psRegistria.ts.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289186/psRegistria.ts.txt)
[registriaData.ts.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289190/registriaData.ts.txt)
[tsconfig.json.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289191/tsconfig.json.txt)
[nodemon.json.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289192/nodemon.json.txt)
[package.json.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289193/package.json.txt)
[registria.ts.txt](https://github.com/GillianPerard/typescript-json-serializer/files/4289194/registria.ts.txt)

**Comment by tleclaire** [comment]
Fixed this by adding "emitDecoratorMetadata":true to the compiler options in tsconfig.json.

{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "experimentalDecorators": true,
    _**"emitDecoratorMetadata":true,**_
    "target": "es5",
    "rootDir": ".",
    "forceConsistentCasingInFileNames": false,
    "outDir": "build"
  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ]
}

**Comment by jaredbaszler** [comment]
But I already had that property "emitDecoratorMetadata" set to true in the attached tsConfig.json?

**Comment by GillianPerard** [comment]
Hi, could you give my a way or the instructions to test your build please?

**Comment by jaredbaszler** [comment]
I run the following commands:
1. npx tsc 
2. cd build
3. pkg -t win registria.js

**Comment by GillianPerard** [comment]
Ok, let me check.

**Comment by hellos3b** [comment]
> Fixed this by adding "emitDecoratorMetadata":true to the compiler options in tsconfig.json.

This worked for me as well

**Comment by GillianPerard** [comment]
In `tsconfig.json` he provided, there is already `emitDecoratorMetadata: true`.

**Comment by kerueter** [comment]
I am also facing this issue, if i want to de-serialize a class which has a base class defined in the`@Serializable` decorator. It seems that `Reflect.getMetadata` fails somehow, if a base class name is provided.

**Comment by GillianPerard** [comment]
You're also in the case where you build a pkg `.exe` and it fails on run?

**Comment by kerueter** [comment]
No, i basically compile a .ts file with `tsc` and execute the resulting .js with `node` afterwards.

**Comment by GillianPerard** [comment]
Ok, could you provide me an example please.

**Comment by kerueter** [comment]
Parent:
`
@Serializable()
export class Parent {
  constructor(
    @JsonProperty({ name: 'id' }) private _id: number,
    @JsonProperty({ name: 'title' }) private _name: string,
    @JsonProperty({ name: 'type' }) private _type: string,
    @JsonProperty({ name: 'duration' }) private _duration?: number,
  ) {
    super();
  }
`

Child:
`
@Serializable('Parent')
export class Child extends Parent {
  constructor(
    _id: number,
    _name: string,
    _type: PlayableType,
    @JsonProperty({ name: 'src' }) private _src: string,
    @JsonProperty({ name: 'lastUploaded' }) private _lastUploaded: number,
    _duration?: number,
    @JsonProperty({ name: 'mimeType' }) private _mimeType?: string
  ) {
    super(_id, _name, _type, _duration);
  }
`

I printed the instance map in the deserialize function and i got `{"undefined":{"name":"src"}}`. Somehow some properties get mixed up in the map and some are missing. Weird.

**Comment by GillianPerard** [comment]
Thank you! I'll check as soon as possible.

**Comment by GillianPerard** [comment]
Hi guys, I've just published the new release 2.0.0, hope it fixes your issue!

**Comment by chrys-exaucet** [comment]
Hi, @GillianPerard , 

I am facing the same issue pointed above.

I am using 

```txt
typescript@4.1.3
typescript-json-serializer@^2.5.2
```

Here is my tsconfig.json:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

A  sample of my code :

```ts
@Serializable()
export abstract class AbstractThing {
  @JsonProperty({ name: 'id' })
   _id: number;
  @JsonProperty({ name: 'type' })
   readonly _type: ThingType;
```


```ts
@Serializable()
export class SomeThing extends AbstractThing {

  @JsonProperty({name:"name"})
   _name: string;
  @JsonProperty({name:"surname"})
_surname: string;
```


```ts
@Serializable()
export class OtherThing extends AbstractThing {

  @JsonProperty({name:"tradeRegister"})
  private _tradeRegister: string;
  @JsonProperty({name:"corporateName"})
  private _corporateName: string;
```

They are called here:

```ts

export async function register(data: AbstractThing): void {

  console.log(thing); // printed on console
  console.log(serialize(thing, false));  //<<<< error here
```

The stack trace:

```txt
Unhandled Rejection (TypeError): Cannot read property 'name' of undefined
▼ 3 stack frames were expanded.
convertPropertyToData
~/node_modules/typescript-json-serializer/index.js:189
(anonymous function)
~/node_modules/typescript-json-serializer/index.js:159
serialize
~/node_modules/typescript-json-serializer/index.js:155
▲ 3 stack frames were expanded.
Module.register

```

**Comment by GillianPerard** [comment]
Hi, let me check!

**Comment by chrys-exaucet** [comment]
Sorry for the late, @GillianPerard!

```thing``` is an object  of class   ```AbstractThing``` oferementionend.

**Comment by GillianPerard** [comment]
Hi, I can't reproduce your problem, could you update the lib and test it again please?

**Comment by chrys-exaucet** [comment]
That's a react project.
 Updating libs ASAP.

**Comment by GillianPerard** [comment]
Do you have some updates?

**Comment by chrys-exaucet** [comment]
Works fine now,  @GillianPerard ! I assume it was a peer dependencies depth. 
That's one one those weird things you can't explain properly. :-)
