### ISSUE TITLE
how to serializer like {[x:number]:ClassA}

### ISSUE THREAD

**Issue by cheny5210** [GillianPerard/typescript-json-serializer#62]
how to serializer like {[x:number]:ClassA}

// 当前装备
class A {
}

class B {
     @JsonProperty() // serializer  error
     ClassA: { [x: number]: A} = {};
}

**Comment by GillianPerard** [comment]
Hi, let me check that.

**Comment by GillianPerard** [comment]
Could you send me the error you get please?
