### ISSUE TITLE
Recursive types that extend another class

### ISSUE THREAD

**Issue by cpkuo** [GillianPerard/typescript-json-serializer#63]
I have a type like:

`@Serializable()
export class Root {
    @JsonProperty({ name: "expressions", predicate: ExpressionType})
    public expressions: Array<Expression>;
}
`

There are two more types that extend Expression, they are:

`@Serializable("Expression")
export class ExpressionGroup extends Expression {
    @JsonProperty({ name: "expressions", predicate: ExpressionType })
    public expressions: Array<Expression>;
}`

AND

`@Serializable("Expression")
export class Statement extends Expression {
    @JsonProperty()
    public field: string;
    @JsonProperty()
    public operator: Operator;
    @JsonProperty()
    public value: string;
}`

When I call deserialize, the Array<Expression> off of Root appears to contain the correct types. However, the first element of this array is an ExpressionGroup, and it's Array<Expression> was not converted into the right types, it is just an Object. Putting a console.log("called") inside the predicate function "ExpressionType" seems to be hit only once, presumably on Root's Array<Expression>.

Is there a limitation in deeply nested arrays?

**Comment by GillianPerard** [comment]
Hi normally not,

Let me check what happened;

**Comment by GillianPerard** [comment]
Could you provide me, the `Expression` class and the `ExpressionType` function as well to be sure that my tests are good please?

**Comment by cpkuo** [comment]
Expression type is:
@Serializable()`
export class Expression {
}`

and ExpressionType function is something like. The code is called in the Array off of the Root.

return expression["$type"].toString().indexOf("Statement") > -1 ? Statement : ExpressionGroup;

**Comment by GillianPerard** [comment]
I tested with the few information you gave me and it works properly.

I used:

```ts
const ExpressionType = (expression: Expression) => (expression['expressions'] ? ExpressionGroup : Statement);

@Serializable()
export class Expression {}

@Serializable()
export class Root {
    @JsonProperty({ predicate: ExpressionType })
    public expressions: Array<Expression>;
}

@Serializable('Expression')
export class ExpressionGroup extends Expression {
    @JsonProperty({ predicate: ExpressionType })
    public expressions: Array<Expression>;
}

@Serializable('Expression')
export class Statement extends Expression {
    @JsonProperty() public field: string;
    @JsonProperty() public value: string;
}

export const dataRoot: any = {
    expressions: [
        {
            expressions: [
                { field: 'test1', value: 'test1value' },
                { field: 'test2', value: 'test2value' }
            ]
        },
        { field: 'test3', value: 'test3value' }
    ]
};
```

I think that your predicate function is the problem.

Another thing, you don't need to specify the `name` inside the `JsonProperty` if the class property name and the one provided by the json you deserialize are the same.
