### ISSUE TITLE
feat: add support for "merging" properties

### ISSUE THREAD

**Issue by kerueter** [GillianPerard/typescript-json-serializer#72]
After the update to 2.0.0 this serializer works like a charm in my project. Thanks!

But to really use this in my project, the feature is missing that i can kinda "merge" the properties from my incoming JSON into one property in my TS class.

Example: 
`@Serializable()
class A {
    @JsonProperty({ names: ["x", "y", "z"], onDeserialize: deserializeNested })
    coordinates: { x: number, y: number, z: number };
}

const data: any = {
    x: 1382,
    y: 3134,
    z: 313
};

const deserialized = deserialize<A>(data, A)`

So that in the function defined in onDeserialize i have an array of the properties i defined in the names in the decorator.

Would it be possible to add this feature to the typescript-json-serializer ?

Thanks in advance!

**Comment by GillianPerard** [comment]
Hi, I'm happy it works pretty well for you!

Let me check what I can do 😊

**Comment by GillianPerard** [comment]
Hi, sorry for the wait. I added a new feature to merge properties. I hope it will work for you!

I let you download the new version 2.1.0!

**Comment by kerueter** [comment]
Hey, the deserialization with merging the properties works, but the serialization requires that it is in the same format as before deserializing (at least the "root" properties defined in "names")?

Kinda unusable if i want to convert from format A to format B. :(

**Comment by GillianPerard** [comment]
Oh... 

Could you provide me the base object you want to deserialize, the result after deserialized and the result seralized please? That will help me to provide the good behavior 😊

**Comment by kerueter** [comment]
Input:
{
    „version“: 1,
    „propertyA“: { innerA1: 0, innerA2: 1},
    „propertyB“: { innerA1: 4, innerA2: 2} 
}

Code: 
@JsonProperty() private version: number;

@JsonProperty({ names: [‚propertyA, ‚propertyB‘], onDeserialize: deserializeProps, onSerialize: serializeProps})
private properties: Array<Property>;

const serializeProps: Function = (properties: Array<any>): Array<any> => {
  const propsSerialized = new Array<any>();

  properties.forEach(prop => {
     propsSerialized.push(serialize(prop));
  }

  return propsSerialized;
}

Output:
{
   „version“: 1
}

Output Expected:
{
   „version“: 1,
   „properties: [
   	…
    ]
}
