### ISSUE TITLE
Deserialize does not handle null

### ISSUE THREAD

**Issue by boekhold** [GillianPerard/typescript-json-serializer#73]
I have a JavaScript object that has some properties as null, eg:

```
const obj = JSON.parse(`{
    "field1": "some string",
    "field2": null,
    "field3": null,
    "field4": "something else"
}`);
```
I have a class using the `@Serializable` and `@JsonProperty` annotations:

```
@Serializable()
export class Dummy {
    @JsonProperty() field1?: string;
    @JsonProperty() field2?: string;
    @JsonProperty() field3?: string;
    @JsonProperty() field4?: string;
}
```
If I try to deserialize my JS object with:

```
const dummy: Dummy = deserialize<Dummy>(obj, Dummy);
```
I get:
```
TypeError: Cannot read property 'toString' of null
```
from `castSimpleData`.

isn't "null" a valid value for a property and shouldn't this be handled? Currently I just use an onDeserialize function that converts null to empty string to get around this.

**Comment by GillianPerard** [comment]
Hi, ok let me check that!

**Comment by boekhold** [comment]
> Hi, ok let me check that!

Note that I had to update my test case code in the first post...

Not sure what the right behavior should be. I think perhaps set the property to undefined...

**Comment by GillianPerard** [comment]
Hi, I fixed it!

I let you download the new version 2.1.0!

**Comment by boekhold** [comment]
I can confirm that version 2.1.0 fixes this issue. Thanks @GillianPerard for the prompt fix!
