### ISSUE TITLE
Nested property of Array<T> does not serialize properly

### ISSUE THREAD

**Issue by wcroteau** [GillianPerard/typescript-json-serializer#76]
Hi Gillian.

First, thanks for you efforts and your contributions!

I'm using typsecript-json-serializer v2.1.0

I've found that properties which are an Array of serializable objects do not serialize correctly...

Given the following model definition:

```
@Serializable()
export class Person {
    @JsonProperty()
    public name: string;
    @JsonProperty()
    public children?: Array<Person>;
    public parent?: Person;
}

```

The `parent ` in this case is NOT decorated with @JsonProperty and therefore should NOT appear when serialized.

However I'm finding that when I perform the following (from my .spec.ts file):

```
        const child = new Person();
        child.name = 'Child';

        const parent = new Person();
        parent.name = 'Parent';
        parent.children = [child];

        child.parent = parent;

        const json = serialize(parent);
        expect(json.children[0].parent).toBeUndefined();

```

I find that my test case is failing as follows:

```
expect(received).toBeUndefined()

    Received: {"children": [{"name": "Child", "parent": [Circular]}], "name": "Parent"}

```

Note that the Parent property has been stripped as expected from the Parent instance but still remains in the child instance.  I have proven this by setting breakpoints and inspecting both the "parent" and "json" objects after serialization.

To prove this theory I created a second class "Person2" whose only difference is that instead of an Array of children I have simply a single child of type Person2:

```
@Serializable()
export class Person2 {
    @JsonProperty()
    public name: string;
    @JsonProperty()
    public child?: Person2;
    public parent?: Person2;
}
```

In this case, the exact same test setup as above passes and inspecting the serialized object yield no Parent property.  

This is true even if I nest further (i.e. Grandparent > Parent > Child).

It therefore appears that the JsonProperty (or lack of in this case) is being ignored when it's an Array...

Is this a bug or have I done something stupid?

**Comment by GillianPerard** [comment]
Hi, thank you for your feedback!

I will check it as soon as possible 😊

**Comment by GillianPerard** [comment]
Hi, after checking your code, I found two mistakes.

The first one is that you create a circular object by referencing the parent inside the child which is itself referenced by this same parent. Even if you try it without my lib you'll get an infinite loop object. I think it's not a good pattern.

The second one is when you want to use `JsonProperty` on an array of class you must specified the class inside the configuration of the `JsonProperty`.
Your class should look like:

```ts
@Serializable()
export class Person {
    @JsonProperty()
    public name: string;
    @JsonProperty({ type: Person })
    public children?: Array<Person>;
    public parent?: Person;
}
```

PS: If you still want to use your implementation, know that your test will pass thanks to the second point I mentioned 😊.

**Comment by wcroteau** [comment]
That fixes it!  I thought I had tried that before posting here but I guess not - sorry for wasting your time.

Regarding the circular references:  I respectfully disagree.  This is a perfectly valid domain design and is common in many cases.  Take for example a classic "linked-list" data structure.  In my case the objects are required to be navigable in both directions.  

I DO however appreciate that this is "simple" when dealing with object references in memory but causes issues when attempting to serialize them (as is the problem here).  That is why my "parent" property is transient.  The plan here is to use a transform function on deSerialize which will re-establish the relationship.

Thanks for your help!

**Comment by GillianPerard** [comment]
Don't worry!

Thank you for your explanation :)

You're welcome!
