### ISSUE TITLE
Feature: Extend Transform Function to Include Reference to Parent Element

### ISSUE THREAD

**Issue by wcroteau** [GillianPerard/typescript-json-serializer#77]
It would be incredibly nice for the transform function to also be passed a reference to the parent element.

Consider the following structure:

```
@Serializable()
export class MyClass {
   @JsonProperty()
   public id: number;
   @JsonProperty()
   public name: string;
   public parent: MyClass;
   @JsonProperty({ type: MyClass, onDeserialize: deserializeChildren })
   public children: Array<MyClass>;
}

...
const parent = new MyClass();
parent.id = 1;
parent.name = 'Parent'

const child = new MyClass();
child.id = 2;
child.name = 'Child';
child.parent = parent;

parent.children = [child1];
...

```

We have previously had discussions around the merits/problems of such a circular reference of the Parent referencing the Child.  This is a necessary navigation in my structure and is perfectly fine until I need to serialize... (circular is fine when we're using references at runtime but problematic when you attempt to serialize unless the framework is "smart" enough to use references...).

At any rate, it's for this reason that the "parent" property of MyClass is transient (i.e. NOT marked as a JsonProperty).  In this way, the parent relationship is stripped on serialize and no circular relationship exists in the serialized structure.

However, the difficulty comes when I attempt to deSerialize...  When resaturating the MyClass instance I need to reestablish the parent relationship...

My original thought was to have a transform function on the "children" attribute and simply populate the parent...  however this necessitates an actual reference to the parent which is not (or doesn't appear to be) available.

Another option would be to have some form of "postSerialize" function that you could attach to the @Serializable() decorator which would permit me to do any number of "cleanup" steps to the instance as a whole (I can envision many reasons that this might be a useful tool).

Either of the two mechanisms above would work for me in my scenario although adding the parent reference to the parameter list of the transform seems somewhat case-specific.

Would either of the above be something you'd consider adding?

Additionally I'd be happy to hear about any other way you can see to solve my problem.

**Comment by GillianPerard** [comment]
Hi, I just push a new version with a `postDeserialize` function you can apply to the json property and access the current instance (the current instance may not yet contain all the properties because it still deserialize) but i think you can pass the ref to your child.

```ts
@Serializable()
export class MyClass {
   @JsonProperty()
   public id: number;
   @JsonProperty()
   public name: string;
   public parent: MyClass;
   @JsonProperty({ type: MyClass, postDeserialize: (property: Array<MyClass>, currentInstance: MyClass) => {
       return property.map(x => {
             x.parent = currentInstance;
             return x;
       }
   }})
   public children: Array<MyClass>;
}
```

**Comment by wcroteau** [comment]
Works like a charm!

Thank-you very much for your efforts.
