### ISSUE TITLE
Serialize any or union type question

### ISSUE THREAD

**Issue by wcroteau** [GillianPerard/typescript-json-serializer#80]
Hi, I have a question about the best way to deserialize an object with a member of type `any`.

Given the following model definition:

```
@Serializable()
export class Squirrel {

    constructor(
        @JsonProperty()
        public color: string,
        @JsonProperty()
        public data?: any
}

```

and then performing the following:

```
        let squirrel = new Squirrel('red', 'bushy-tailed-rat');
        let json = serialize(squirrel);
        const jsonString = JSON.stringify(json, null, 3);
        console.log(jsonString);

        json = JSON.parse(jsonString);
        squirrel = deserialize<Squirrel>(json, Squirrel);

```

This "works" however the `data` loses all type information when I use a non-primitive type - (not what I need)...

```
@Serializable()
export class NutData {

    constructor(
        @JsonProperty()
        public species: string
    ) { }

}

...
        let squirrel = new Squirrel('Red', new NutData('Oak'));
        let json = serialize(squirrel);
        const jsonString = JSON.stringify(json, null, 3);
        console.log(jsonString);

        json = JSON.parse(jsonString);
        squirrel = deserialize<Squirrel>(json, Squirrel);
...
```

The difficulty for is that the `data` member can be a number of different types including the primitive types `string` or `number`.

I've tried a number of different solutions... option 1: using a `predicate` and maintaining the data type of `any`:

```
export const dataPredicate = attribute => {

    if (attribute['species'] !== undefined) {
        return NutData;
    }

    if (typeof attribute === 'number') {
        return Number; // this is suspect however using 'number' results in a compile error.
    }

    if (typeof attribute === 'string') {
        return String; // also suspect...
    }
};

@Serializable()
export class Squirrel {

    constructor(
        @JsonProperty()
        public color: string,
        @JsonProperty({ predicate: dataPredicate })
        public data?: any) { }

}
```

Running this through my test scripts yields the following error: 

```
TypeError:

      249 |     );
      250 |     const apiMapInstanceName = `${apiMap}${instanceName}`;
    > 251 |     const hasMap = Reflect.hasMetadata(apiMapInstanceName, instance);
          |                            ^
      252 |     let instanceMap: { [id: string]: Metadata } = {};
      253 | 
      254 |     if (!hasMap && (!baseClassNames || !baseClassNames.length)) {

      at Object.hasMetadata (node_modules/reflect-metadata/Reflect.js:270:23)
      at serialize (src/index.ts:251:28)
      at convertPropertyToData (src/index.ts:324:16)
      at src/index.ts:269:24
          at Array.forEach (<anonymous>)
      at Object.serialize (src/index.ts:265:30)
      at Object.<anonymous> (spec/index.spec.ts:325:16)
```

I note that the predicate is never even evaluated...  So I then attempted to use a union type:

```
@Serializable()
export class Squirrel {

    constructor(
        @JsonProperty()
        public color: string,
        @JsonProperty({ predicate: dataPredicate })
        public data?: NutData | string | number) { }

}

```

This resulted in an identical error leading me to believe that there's something fundamentally wrong with what I'm doing.

Can you suggest what the configuration should be in the above scenario?

I have considered wrapping all possibilities in an 'DataClass' class but this doesn't seem to be terribly maintainable:

```
@Serializable()
export class DataClass {

    constructor(
        @JsonProperty()
        public nutData?: NutData,
        @JsonProperty()
        public stringData?: string,
        @JsonProperty()
        public numberData?: number
    ) { }
}

@Serializable()
export class Squirrel {

    constructor(
        @JsonProperty()
        public color: string,
        @JsonProperty()
        public data?: DataClass) { }

}
```

Any suggestions would be greatly appreciated!

**Comment by GillianPerard** [comment]
Hi sorry to be late, 

I think the best way is to use union type like `NutData | string | number` to document your code but in the predicate all the native type are manage in the same way so if it's `string` or `number` you don't have to return a specific type.

I'm really busy this week, so could you test it and if it not works I'll check that as soon as possible 😊.

**Comment by wcroteau** [comment]
Hi Gillian,

No problem - I understand that you have other things going on.

I've tested your proposed solution and I still get the same problem.

To be clearer - this is actually happening on the `serialize` call and not the `deserialize `as I first suggested (I was testing deserializing and apparently missed that this exception was being thrown when I first serialize the object...).  I've updated the title accordingly.

That said, I still get the problem at line 251 as above on the call to `Reflect.hasMetaData()`.

**Comment by GillianPerard** [comment]
Hi, I can't reproduce...

Just one question why are you using `JSON.stringify` and `JSON.parse` in your example:

```ts
...
        let squirrel = new Squirrel('Red', new NutData('Oak'));
        let json = serialize(squirrel);
        const jsonString = JSON.stringify(json, null, 3);
        console.log(jsonString);

        json = JSON.parse(jsonString);
        squirrel = deserialize<Squirrel>(json, Squirrel);
...
``` 

I've tried something like this and I got the correct type:

```ts
@Serializable()
export class NutData {
    @JsonProperty()
    public id = 42;
    @JsonProperty()
    public value = 'lala';
}

@Serializable()
export class Squirrel {
    constructor(
        @JsonProperty()
        public color: string,
        @JsonProperty()
        public d?: NutData | string | number
    ) {}
}

let squirrel = new Squirrel('red', new NutData());
const json = serialize(squirrel);
console.log(json);
squirrel = deserialize<Squirrel>(json, Squirrel); 
console.log(squirrel);
console.log(squirrel.d instanceof NutData);
console.log(typeof squirrel);
```

**Comment by wcroteau** [comment]
Hi Gillian,

I use JSON.stringify and JSON.parse in order to simulate the round-trip to the database (the real reason that I'm trying to use your library).  At current my database does not support JSON objects directly so I'm storing the stringified version.

This in part answers you other question.

The stringify/parse seems to be the ultimate culprit here...  If you insert a stringify then parse between your serialize() and deserialize() calls you will see my problem...

Your solution as written will result in the d property being re-saturated as an Object and not a NutData instance (i.e. type information is lost).

Your solution above works for you because the json object in fact doesn't seem to have been called on all properties...  If you inspect your json object after serialize you'll notice that the d property still has type information... I would have expected it to be a "pure" Object with NO type information...  Is this a bug with the serialize function or have I misunderstood something.

Thanks!

**Comment by GillianPerard** [comment]
Ok, I see. I think it comes from my serialize function, I will try to fix it!

**Comment by GillianPerard** [comment]
Hi, I found a solution, let me implement it and add some unit tests.

I'll publish the new release today 😊

**Comment by GillianPerard** [comment]
Hi, the new release 2.3.0 is now available!

You can use your class like this:

```ts
@Serializable()
export class Squirrel {
    constructor(
        @JsonProperty() public color: string,
        @JsonProperty({predicate: property => {
            if (property && property.id !== undefined) {
                return NutData;
            }
        }})
        public d?: NutData | string | number
    ) {}
}
```

Sorry again for the time, I hope it will help you 😊.
