### ISSUE TITLE
JsonSerializable Class inherited in --prod build does not get JsonProperty

### ISSUE THREAD

**Issue by hoploop** [GillianPerard/typescript-json-serializer#81]
Steps to reproduce:
- Create a Serializable Class that extends another Serializable class, with at least one more JsonProperty
- Observe correct serialization behavior in test mode with experimentalDecorators:True
- COmpile --prod
- Observe the additional JsonProperty is not populated by the constructors in prod build

**Comment by GillianPerard** [comment]
Hi,

In which kind of project do you use my lib? Node, Angular, React, another?

**Comment by hoploop** [comment]
Angular. I discovered that if I put the JsonProperty not in the constructor the problem doesn't appear.
So it happens when you extend a Serializable class with normal JsonProperty in the class to a class with JsonProperty in the constructor.

**Comment by GillianPerard** [comment]
At this moment, Typescript-json-serializer not working with Angular.
