### ISSUE TITLE
ts 2307 

### ISSUE THREAD

**Issue by vinceboilay** [GillianPerard/typescript-json-serializer#93]
I am brand new to typescript, VS code and all that stuff.

I have installed using npm install typescript-json-serializer --save as per the documentation

but I have an error shown in VS code : Cannot find module 'typescript-json-serializer' or its corresponding type declarations.ts(2307)
on this line :
import { JsonProperty, Serializable, deserialize, serialize } from 'typescript-json-serializer';

My project is using node.

my options are like:
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,    
    "target": "es5",
    "module": "es6",    
    "pretty": false,
    "sourceMap": true
  },

when I change "module" to "commonjs" like this  I don't have the error shown in VS code

my options are like:
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,        
    "target": "es5",
    "module": "commonjs",
    "pretty": false,
    "sourceMap": true
  },
the program compiles but when it starst, right after the browser opened I get:
Uncaught ReferenceError: require is not defined

I am very sorry if this looks stupid to you meanwhile I would appreciate some guidance.
Thx

**Comment by vinceboilay** [comment]
Fixed. problem does not exist in a angular project.

**Comment by GillianPerard** [comment]
Hi, take care using this lib inside angular project, if you use `@JsonProperty(...)` inside the constructor params, it will be removed by Angular, you need to use it only when you declare your properties.
