### ISSUE TITLE
Attributes to serialize a dictionnary

### ISSUE THREAD

**Issue by vinceboilay** [GillianPerard/typescript-json-serializer#94]
Hello,
Serialising an Array<ColumnReference > requires JsonProperty to be like
  @JsonProperty( {type: ColumnReference }) 
  public columns: Array \<ColumnReference> = [];

Now I guess that there must be some JsonProperty to specify for a dictionary defined like:
  public  someDic: { [id: string]:  ColumnReference } = {};

can one tell me what should @JsonProperty be for the above example ?

Thanks.

**Comment by GillianPerard** [comment]
Hi, let me check.

**Comment by vinceboilay** [comment]
merci beaucoup ! me manque juste ca pour etre presque heureux :-)

**Comment by vinceboilay** [comment]
I have this ugly workaround

@JsonProperty({ onDeserialize: deserMe }) //, onSerialize: serMe })  
public someDic: { [id: string]: ColumnReference } = {};

function deserMe(dic:{ [id: string]: ColumnReference })
{    
  let res:{ [id: string]: ColumnReference }={};
  Object.entries(dic).forEach(([K, V]) => res[K]= deserialize<ColumnReference>(V, ColumnReference));
  return res;  
}

I tried to get deserMe generic with this in mind:
function deserMe<T>(dic:{ [id: string]: T })
{    
  let res:{ [id: string]: T }={};
  Object.entries(dic).forEach(([K, V]) => res[K]= deserialize<T>(V, T));
  return res;  
}

but I am not good enough in typescript to get it to work.
I saw this : export declare function deserialize<T>(json: object, type: new (...params: Array<any>) => T): T;
I cannot understand what does this type: new (...params: Array<any>) => T

**Comment by GillianPerard** [comment]
Hi, sorry to be late.

I added a new option called `isDictionary` that you must set to `true` and you need to specify the focused class if needed.

```ts
@JsonProperty({ type; ColumnReference, isDictionary: true })
public someDic: { [id: string]: ColumnReference } = {};
```
