### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by omarbelkhodja** [GillianPerard/typescript-json-serializer#99]
After adding an import to the following class, I'm facing an error:

```java
@Serializable()
export class MyClass1 {
    @JsonProperty() id: string = '1';
}
```

```
Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at getJsonPropertyValue (index.js?c608:284)
    at eval (index.js?c608:85)
    at Object.decorateElement (myclass1.ts:23)
    at Object.eval (myclass1.ts:23)
    at Array.forEach (<anonymous>)
    at Object.decorateClass (myclass1.ts:23)
    at _decorate (myclass1.ts:21)
    at eval (myclass1.ts?eef3:6)
    at Module../src/libraries/my-lib/myclass1.ts (0.js:1959)
    at __webpack_require__ (app.js:833)
```

**Comment by GillianPerard** [comment]
Hi, could you tell me what kind of project you are building: React, Angular, NodeJS, another one?

**Comment by omarbelkhodja** [comment]
I'm building [pwa-webpack-starter-kit](https://github.com/Dabolus/pwa-webpack-starter-kit).

**Comment by GillianPerard** [comment]
Ok.

Did you add `"emitDecoratorMetadata": true` and `"experimentalDecorators": true` inside your `tsconfig.json` file?

**Comment by omarbelkhodja** [comment]
Yes, they are already there. I think there is a specific issue related to babel/webpack compiling of TS.

**Comment by GillianPerard** [comment]
I know that babel does not support `emitDecoratorMetadata`, but webpack should work, let me inspecting.

**Comment by omarbelkhodja** [comment]
Did you succeed to reproduce the problem ?

**Comment by GillianPerard** [comment]
I'm currently working on another project for the moment, I'll give you some feedbacks when I have information.

**Comment by omarbelkhodja** [comment]
My current debug results: the problem happens because only target is defined
```javascript
function JsonProperty(args) {
    return function (target, key, index)
```
`decorators[i]` is a reference to JsonProperty

``` javascript
        decorateElement: function decorateElement(element, placements) {
            var extras = [];
            var finishers = [];
            for (var decorators = element.decorators, i = decorators.length - 1; i >= 0; i--) {
                var keys = placements[element.placement];
                keys.splice(keys.indexOf(element.key), 1);
                var elementObject = this.fromElementDescriptor(element);
                var elementFinisherExtras = this.toElementFinisherExtras( (0, decorators[i])(elementObject) || elementObject);
```

**Comment by omarbelkhodja** [comment]
Adding `legacy: true` in Babel configuration fixes the issue (but creates a failure somewhere else). The issue is for sure not in the typescript-json-serializer package itself. I think we can close this issue.

```javascript
['@babel/proposal-decorators', {
      legacy: true
}]
```

**Comment by GillianPerard** [comment]
Thank you for your investigation, yes it seems 😕

**Comment by saileshbro** [comment]
I am getting the same issue. I am using it in cloud functions

**Comment by saileshbro** [comment]
I am not sure what happened, i was using JSdoc comments, and it was fixed after i removed the comments.
